# Copyright 2026 The Outline Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM nginx:1.27-alpine

ENV SB_API_HOST=127.0.0.1
ENV SB_API_PORT=61895
ENV SB_API_PREFIX=changeme
ENV NGINX_ENVSUBST_FILTER=SB_
ENV NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf.template /etc/nginx/templates/nginx.conf.template
COPY static/ /usr/share/nginx/html/
EXPOSE 8080
